from __future__ import annotations

import subprocess
import sys

import pytest


@pytest.mark.parametrize(
    ("module_name", "blocked_module"),
    [
        ("jarvis.tools.services_domains.planner_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_runtime", "jarvis.tools.services"),
        ("jarvis.runtime_telemetry", "jarvis.__main__"),
        ("jarvis.runtime_state", "jarvis.__main__"),
        ("jarvis.runtime_startup", "jarvis.__main__"),
        ("jarvis.runtime_voice_profile", "jarvis.__main__"),
        ("jarvis.runtime_operator_status", "jarvis.__main__"),
        ("jarvis.runtime_observability_status", "jarvis.__main__"),
        ("jarvis.runtime_conversation", "jarvis.__main__"),
        ("jarvis.runtime_preferences", "jarvis.__main__"),
        ("jarvis.runtime_multimodal", "jarvis.__main__"),
        ("jarvis.tools.services_proactive_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_status_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_status_snapshots_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_status_scorecard_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_status_integration_identity_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_status_voice_observability_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_status_expansion_health_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_governance_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_governance_status_payload", "jarvis.tools.services"),
        ("jarvis.tools.services_governance_contract", "jarvis.tools.services"),
        ("jarvis.tools.services_governance_contract_core_fields", "jarvis.tools.services"),
        ("jarvis.tools.services_governance_contract_operational_fields", "jarvis.tools.services"),
        ("jarvis.tools.services_governance_contract_expansion_fields", "jarvis.tools.services"),
        ("jarvis.tools.services_recovery_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_recovery_journal_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_dead_letter_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_recovery_response_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_runtime_state", "jarvis.tools.services"),
        ("jarvis.tools.services_runtime_state_bind", "jarvis.tools.services"),
        ("jarvis.tools.services_runtime_state_reports", "jarvis.tools.services"),
        ("jarvis.tools.services_runtime_state_persistence", "jarvis.tools.services"),
        ("jarvis.tools.services_runtime_state_serialize_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_runtime_state_load_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_audit_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_audit_crypto_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_audit_event_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_audit_sanitize_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_audit_retention_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_ha_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_ha_http_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_ha_http_state_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_ha_http_actions_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_ha_response_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_integrations_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_integrations_release_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_integrations_notes_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_schedule_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_schedule_parse_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_schedule_state_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_defaults", "jarvis.tools.services"),
        ("jarvis.tools.services_preview_facade_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_circuit_facade_runtime", "jarvis.tools.services"),
        ("jarvis.tools.services_audit_facade_runtime", "jarvis.tools.services"),
        ("jarvis.tools.service_schemas", "jarvis.tools.services"),
        ("jarvis.tools.service_schemas_home", "jarvis.tools.services"),
        ("jarvis.tools.service_schemas_comms", "jarvis.tools.services"),
        ("jarvis.tools.service_schemas_memory", "jarvis.tools.services"),
        ("jarvis.tools.service_schemas_advanced", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_memory", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_identity", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_state", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_state_smart_state", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_state_capabilities_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_orchestrator", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_orch_plan_exec", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_orch_automation", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_orch_tasks", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_orch_automation_apply_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_orch_automation_rollback_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_orch_automation_status_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_control", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_mutation", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_mutation_preflight", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_mutation_policy", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_mutation_policy_validate_identity", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_mutation_policy_guardrails", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_mutation_state_checks", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_mutation_execute", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_tools", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_conversation", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_conversation_preflight", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_conversation_execute", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_todo", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_todo_preflight", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_todo_list_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_todo_mutate_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_timer", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_timer_preflight", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_timer_state_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_timer_mutate_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_ha_area_media", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_area_entities_tool", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_media_control_tool", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_media_control_preflight", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_media_control_execute", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.comms_notifications", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.comms_notify_webhooks", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.comms_notify_slack", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.comms_notify_discord", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.comms_notify_pushover", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.comms_email", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.comms_email_send_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.comms_email_summary_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.comms_todoist", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.comms_todoist_add", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.comms_todoist_list", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.governance_tool_summary", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.governance_skills", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.governance_skills_governance", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.governance_skills_actions_a", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.governance_skills_actions_b", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.governance_skills_actions_c", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.governance_skills_registry", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.governance_quality", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.governance_quality_evaluator_actions", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.governance_quality_embodiment_actions", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.governance_status", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_hub", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_hub_calendar_notes", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_hub_messaging", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_hub_release_channels", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_ops", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_weather", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_webhook", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_webhook_trigger", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_webhook_trigger_preflight", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_webhook_trigger_execute", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_webhook_inbound", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_calendar", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_calendar_common", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_calendar_events_list", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_calendar_next", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.integrations_deadletter", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_engine_domain", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_engine_plan_graph", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_engine_plan_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_engine_task_graph_actions", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_engine_self_critique_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_engine_deferred", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_engine_autonomy", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_engine_autonomy_schedule_checkpoint", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_engine_autonomy_cycle", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_engine_autonomy_status", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_schedule", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_timers", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_timers_create", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_timers_list_cancel", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_reminders", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_reminders_crud", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_reminders_create", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_reminders_list_complete", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_reminders_notify", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_taskplan", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_taskplan_create_action", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_taskplan_list_update_actions", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.planner_taskplan_summary_next_actions", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_memory_ops", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_memory_query", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_memory_search", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_memory_recent", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_memory_status_view", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_memory_summary", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_memory_governance", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_orch_automation_suggest_create", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.home_orch_automation_apply_status", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_proactive_briefing", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_proactive_nudges", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_proactive_anomaly", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_proactive_nudge_decision", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_proactive_nudge_decision_classify", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_proactive_nudge_decision_finalize", "jarvis.tools.services"),
        ("jarvis.tools.services_domains.trust_proactive_followthrough", "jarvis.tools.services"),
    ],
)
def test_runtime_module_import_boundary(module_name: str, blocked_module: str) -> None:
    code = (
        "import importlib, sys;"
        f"importlib.import_module('{module_name}');"
        f"print('loaded=' + str('{blocked_module}' in sys.modules))"
    )
    proc = subprocess.run(
        [sys.executable, "-c", code],
        capture_output=True,
        text=True,
        check=True,
    )
    assert "loaded=False" in proc.stdout.strip()
