"""Core system-status contract field groups."""

from __future__ import annotations

from typing import Any

SYSTEM_STATUS_CONTRACT_CORE_FIELDS: dict[str, Any] = {
    "top_level_required": [
        "schema_version",
        "local_time",
        "home_assistant_configured",
        "home_conversation_enabled",
        "todoist_configured",
        "pushover_configured",
        "motion_enabled",
        "home_tools_enabled",
        "memory_enabled",
        "backchannel_style",
        "persona_style",
        "tool_policy",
        "timers",
        "reminders",
        "voice_attention",
        "turn_timeouts",
        "integrations",
        "identity",
        "skills",
        "observability",
        "scorecard",
        "plan_preview",
        "retention_policy",
        "recovery_journal",
        "dead_letter_queue",
        "expansion",
        "memory",
        "audit",
        "recent_tools",
        "health",
    ],
    "tool_policy_required": [
        "allow_count",
        "deny_count",
        "home_permission_profile",
        "safe_mode_enabled",
        "home_require_confirm_execute",
        "home_conversation_enabled",
        "home_conversation_permission_profile",
        "todoist_permission_profile",
        "notification_permission_profile",
        "nudge_policy",
        "nudge_quiet_hours_start",
        "nudge_quiet_hours_end",
        "nudge_quiet_window_active",
        "email_permission_profile",
        "memory_pii_guardrails_enabled",
        "memory_ingestion_min_confidence",
        "memory_ingest_async_enabled",
        "identity_enforcement_enabled",
        "identity_default_profile",
        "identity_require_approval",
        "plan_preview_require_ack",
    ],
    "timers_required": [
        "active_count",
        "next_due_in_sec",
    ],
    "reminders_required": [
        "pending_count",
        "completed_count",
        "due_count",
        "next_due_in_sec",
    ],
    "voice_attention_required": [
        "mode",
        "followup_active",
        "sleeping",
        "active_room",
        "adaptive_silence_timeout_sec",
        "speech_rate_wps",
        "interruption_likelihood",
        "turn_choreography",
        "stt_diagnostics",
        "voice_profile_user",
        "voice_profile",
        "voice_profile_count",
        "acoustic_scene",
        "preference_learning",
        "multimodal_grounding",
    ],
    "voice_attention_acoustic_scene_required": [
        "last_doa_angle",
        "last_doa_speech",
        "last_doa_age_sec",
        "attention_confidence",
        "attention_source",
    ],
    "voice_attention_preference_learning_required": [
        "user",
        "updates",
        "applied_at",
        "source_text",
    ],
    "voice_attention_multimodal_grounding_required": [
        "overall_confidence",
        "confidence_band",
        "attention_source",
        "modality_scores",
        "signals",
        "reasons",
    ],
    "voice_attention_turn_choreography_required": [
        "phase",
        "label",
        "turn_lean",
        "turn_tilt",
        "turn_glance_yaw",
        "updated_at",
    ],
    "voice_attention_stt_diagnostics_required": [
        "source",
        "fallback_used",
        "confidence_score",
        "confidence_band",
        "avg_logprob",
        "avg_no_speech_prob",
        "language",
        "language_probability",
        "segment_count",
        "word_count",
        "char_count",
        "updated_at",
        "error",
    ],
    "voice_attention_voice_profile_required": [
        "verbosity",
        "confirmations",
        "pace",
        "tone",
    ],
    "turn_timeouts_required": [
        "watchdog_enabled",
        "listen_sec",
        "think_sec",
        "speak_sec",
        "act_sec",
    ],
}
