"""Operational status contract field groups."""

from __future__ import annotations

from typing import Any

SYSTEM_STATUS_CONTRACT_OPERATIONAL_FIELDS: dict[str, Any] = {
    "integrations_required": [
        "home_assistant",
        "todoist",
        "pushover",
        "weather",
        "webhook",
        "email",
        "channels",
    ],
    "integration_circuit_breaker_required": [
        "open",
        "open_remaining_sec",
        "consecutive_failures",
        "opened_count",
        "cooldown_sec",
        "last_error",
        "last_failure_at",
        "last_success_at",
    ],
    "identity_required": [
        "enabled",
        "default_user",
        "default_profile",
        "require_approval",
        "approval_code_configured",
        "trusted_user_count",
        "trusted_users",
        "profile_count",
        "user_profiles",
        "trust_policy_count",
        "trust_policies",
        "guest_sessions_active",
        "guest_sessions",
        "household_profile_count",
        "household_profiles",
    ],
    "skills_required": [
        "enabled",
        "loaded_count",
        "enabled_count",
        "skills",
    ],
    "observability_required": [
        "enabled",
        "uptime_sec",
        "restart_count",
        "intent_metrics",
        "multimodal_metrics",
        "alerts",
        "latency_dashboards",
        "policy_decision_analytics",
    ],
    "observability_multimodal_metrics_required": [
        "turn_count",
        "avg_confidence",
        "low_confidence_count",
        "low_confidence_rate",
    ],
    "observability_intent_metrics_required": [
        "turn_count",
        "answer_intent_count",
        "action_intent_count",
        "hybrid_intent_count",
        "answer_sample_count",
        "completion_sample_count",
        "answer_quality_success_rate",
        "completion_success_rate",
        "correction_count",
        "correction_frequency",
        "preference_update_turns",
        "preference_update_fields",
    ],
    "observability_latency_dashboards_required": [
        "sample_count",
        "overall_total_ms",
        "by_intent",
        "by_tool_mix",
        "by_wake_mode",
    ],
    "observability_latency_bucket_required": [
        "p50",
        "p95",
        "p99",
    ],
    "observability_policy_decision_analytics_required": [
        "decision_count",
        "by_tool",
        "by_status",
        "by_reason",
        "by_user",
        "by_user_tool",
    ],
    "scorecard_required": [
        "overall",
        "dimensions",
        "weights",
        "computed_at",
    ],
    "scorecard_overall_required": [
        "score",
        "grade",
    ],
    "scorecard_dimensions_required": [
        "latency",
        "reliability",
        "initiative",
        "trust",
    ],
    "scorecard_dimension_required": [
        "score",
        "grade",
    ],
    "plan_preview_required": [
        "pending_count",
        "ttl_sec",
        "strict_mode",
    ],
    "retention_policy_required": [
        "memory_retention_days",
        "audit_retention_days",
    ],
    "recovery_journal_required": [
        "path",
        "exists",
        "entry_count",
        "tracked_actions",
        "unresolved_count",
        "interrupted_count",
        "recent",
    ],
    "dead_letter_queue_required": [
        "path",
        "exists",
        "entry_count",
        "pending_count",
        "failed_count",
        "replayed_count",
        "recent",
    ],
}
