"""Service tool schemas and runtime required-field contracts."""

from __future__ import annotations

from typing import Any

SERVICE_TOOL_SCHEMAS: dict[str, dict[str, Any]] = {
    "smart_home": {
        "type": "object",
        "properties": {
            "domain": {
                "type": "string",
                "description": "HA domain: light, switch, climate, media_player, lock, cover, etc.",
            },
            "action": {
                "type": "string",
                "description": "Service to call: turn_on, turn_off, toggle, set_temperature, etc.",
            },
            "entity_id": {
                "type": "string",
                "description": "Entity ID, e.g. light.living_room, climate.thermostat.",
            },
            "data": {
                "type": "object",
                "description": "Optional service data (brightness, temperature, etc.).",
            },
            "dry_run": {
                "type": "boolean",
                "description": "If true, describe what would happen without executing. "
                "Always true for locks/alarms/covers unless user explicitly confirms.",
            },
            "confirm": {"type": "boolean", "description": "Optional explicit confirmation for execute paths."},
            "requester_id": {"type": "string", "description": "Requester identity for policy decisions and audit."},
            "request_context": {"type": "object", "description": "Optional voice/text context with requester metadata."},
            "speaker_verified": {"type": "boolean", "description": "Trusted-speaker hook for voice identity pipelines."},
            "approved": {"type": "boolean", "description": "Trusted approval handshake flag for high-risk actions."},
            "approval_code": {"type": "string", "description": "Approval code for high-risk actions when required."},
            "preview_only": {"type": "boolean", "description": "Return plan preview without executing."},
            "preview_token": {"type": "string", "description": "Plan preview token required when preview acknowledgment is enforced."},
            "require_preview_ack": {"type": "boolean", "description": "If true, require preview_token before execution."},
        },
        "required": ["domain", "action", "entity_id"],
    },
    "smart_home_state": {
        "type": "object",
        "properties": {
            "entity_id": {"type": "string"},
        },
        "required": ["entity_id"],
    },
    "home_assistant_capabilities": {
        "type": "object",
        "properties": {
            "entity_id": {"type": "string"},
            "include_services": {"type": "boolean"},
        },
        "required": ["entity_id"],
    },
    "home_assistant_conversation": {
        "type": "object",
        "properties": {
            "text": {"type": "string", "description": "Natural language command for HA conversation agent."},
            "language": {"type": "string", "description": "Optional language code (for example en)."},
            "agent_id": {"type": "string", "description": "Optional Home Assistant conversation agent id."},
            "confirm": {
                "type": "boolean",
                "description": "Must be true for execution to reduce accidental high-impact voice commands.",
            },
            "requester_id": {"type": "string", "description": "Requester identity for policy decisions and audit."},
            "request_context": {"type": "object", "description": "Optional voice/text context with requester metadata."},
            "speaker_verified": {"type": "boolean", "description": "Trusted-speaker hook for voice identity pipelines."},
            "approved": {"type": "boolean", "description": "Trusted approval handshake flag for high-risk actions."},
            "approval_code": {"type": "string", "description": "Approval code for high-risk actions when required."},
            "preview_only": {"type": "boolean", "description": "Return plan preview without executing."},
            "preview_token": {"type": "string", "description": "Plan preview token required when preview acknowledgment is enforced."},
            "require_preview_ack": {"type": "boolean", "description": "If true, require preview_token before execution."},
        },
        "required": ["text"],
    },
    "home_assistant_todo": {
        "type": "object",
        "properties": {
            "action": {"type": "string", "description": "list, add, or remove"},
            "entity_id": {"type": "string", "description": "Todo entity id, for example todo.shopping"},
            "item": {"type": "string", "description": "Todo item text for add/remove actions"},
            "item_id": {"type": "string", "description": "Optional uid for remove actions"},
            "status": {"type": "string", "description": "Optional status filter for list actions"},
            "requester_id": {"type": "string"},
            "request_context": {"type": "object"},
            "speaker_verified": {"type": "boolean"},
            "approved": {"type": "boolean"},
            "approval_code": {"type": "string"},
        },
        "required": ["action", "entity_id"],
    },
    "home_assistant_timer": {
        "type": "object",
        "properties": {
            "action": {"type": "string", "description": "state, start, pause, cancel, or finish"},
            "entity_id": {"type": "string", "description": "Timer entity id, for example timer.kitchen"},
            "duration": {"type": "string", "description": "Optional duration when action=start (HH:MM:SS)."},
            "requester_id": {"type": "string"},
            "request_context": {"type": "object"},
            "speaker_verified": {"type": "boolean"},
            "approved": {"type": "boolean"},
            "approval_code": {"type": "string"},
        },
        "required": ["action", "entity_id"],
    },
    "home_assistant_area_entities": {
        "type": "object",
        "properties": {
            "area": {"type": "string", "description": "Home Assistant area name."},
            "domain": {"type": "string", "description": "Optional entity domain filter (light, switch, climate, etc.)."},
            "include_states": {"type": "boolean", "description": "Include live entity states in response."},
        },
        "required": ["area"],
    },
    "media_control": {
        "type": "object",
        "properties": {
            "entity_id": {"type": "string", "description": "media_player entity id"},
            "action": {"type": "string", "description": "play, pause, stop, volume_set, mute, unmute"},
            "volume": {"type": "number", "description": "Volume level between 0.0 and 1.0 for volume_set."},
            "dry_run": {"type": "boolean"},
            "requester_id": {"type": "string"},
            "request_context": {"type": "object"},
            "speaker_verified": {"type": "boolean"},
            "approved": {"type": "boolean"},
            "approval_code": {"type": "string"},
            "preview_only": {"type": "boolean"},
            "preview_token": {"type": "string"},
            "require_preview_ack": {"type": "boolean"},
        },
        "required": ["entity_id", "action"],
    },
    "weather_lookup": {
        "type": "object",
        "properties": {
            "location": {"type": "string"},
            "units": {"type": "string", "description": "metric or imperial"},
        },
        "required": ["location"],
    },
    "webhook_trigger": {
        "type": "object",
        "properties": {
            "url": {"type": "string"},
            "method": {"type": "string"},
            "payload": {"type": "object"},
            "headers": {"type": "object"},
            "timeout_sec": {"type": "number"},
            "requester_id": {"type": "string"},
            "request_context": {"type": "object"},
            "speaker_verified": {"type": "boolean"},
            "approved": {"type": "boolean"},
            "approval_code": {"type": "string"},
            "preview_only": {"type": "boolean"},
            "preview_token": {"type": "string"},
            "require_preview_ack": {"type": "boolean"},
        },
        "required": ["url"],
    },
    "webhook_inbound_list": {
        "type": "object",
        "properties": {
            "limit": {"type": "integer"},
        },
    },
    "webhook_inbound_clear": {
        "type": "object",
        "properties": {},
    },
    "slack_notify": {
        "type": "object",
        "properties": {
            "message": {"type": "string"},
            "requester_id": {"type": "string"},
            "request_context": {"type": "object"},
            "speaker_verified": {"type": "boolean"},
            "approved": {"type": "boolean"},
            "approval_code": {"type": "string"},
        },
        "required": ["message"],
    },
    "discord_notify": {
        "type": "object",
        "properties": {
            "message": {"type": "string"},
            "requester_id": {"type": "string"},
            "request_context": {"type": "object"},
            "speaker_verified": {"type": "boolean"},
            "approved": {"type": "boolean"},
            "approval_code": {"type": "string"},
        },
        "required": ["message"],
    },
    "email_send": {
        "type": "object",
        "properties": {
            "to": {"type": "string"},
            "subject": {"type": "string"},
            "body": {"type": "string"},
            "confirm": {"type": "boolean"},
            "requester_id": {"type": "string"},
            "request_context": {"type": "object"},
            "speaker_verified": {"type": "boolean"},
            "approved": {"type": "boolean"},
            "approval_code": {"type": "string"},
            "preview_only": {"type": "boolean"},
            "preview_token": {"type": "string"},
            "require_preview_ack": {"type": "boolean"},
        },
        "required": ["subject", "body"],
    },
    "email_summary": {
        "type": "object",
        "properties": {
            "limit": {"type": "integer"},
        },
    },
    "dead_letter_list": {
        "type": "object",
        "properties": {
            "limit": {"type": "integer"},
            "status": {"type": "string"},
        },
    },
    "dead_letter_replay": {
        "type": "object",
        "properties": {
            "entry_id": {"type": "string"},
            "limit": {"type": "integer"},
            "status": {"type": "string"},
        },
    },
    "timer_create": {
        "type": "object",
        "properties": {
            "duration": {
                "description": "Duration in seconds (number) or string like '90s', '5m', '1h 15m'.",
            },
            "label": {"type": "string"},
        },
        "required": ["duration"],
    },
    "timer_list": {
        "type": "object",
        "properties": {
            "include_expired": {"type": "boolean"},
        },
    },
    "timer_cancel": {
        "type": "object",
        "properties": {
            "timer_id": {"type": "integer"},
            "label": {"type": "string"},
        },
    },
    "reminder_create": {
        "type": "object",
        "properties": {
            "text": {"type": "string"},
            "due": {
                "description": "Due timestamp as epoch seconds, ISO datetime, or relative duration like 'in 20m' / '45m'.",
            },
        },
        "required": ["text", "due"],
    },
    "reminder_list": {
        "type": "object",
        "properties": {
            "include_completed": {"type": "boolean"},
            "limit": {"type": "integer"},
        },
    },
    "reminder_complete": {
        "type": "object",
        "properties": {
            "reminder_id": {"type": "integer"},
        },
        "required": ["reminder_id"],
    },
    "reminder_notify_due": {
        "type": "object",
        "properties": {
            "limit": {"type": "integer"},
            "title": {"type": "string"},
            "nudge_policy": {"type": "string", "description": "interrupt, defer, or adaptive (optional override)."},
            "urgent_overdue_sec": {"type": "number", "description": "When nudge_policy=adaptive and quiet hours are active, overdue reminders beyond this threshold still send."},
        },
    },
    "calendar_events": {
        "type": "object",
        "properties": {
            "calendar_entity_id": {"type": "string"},
            "start": {"type": "string", "description": "Optional start datetime (ISO)."},
            "end": {"type": "string", "description": "Optional end datetime (ISO)."},
            "window_hours": {"type": "number", "description": "Window size when end is omitted."},
            "limit": {"type": "integer"},
        },
    },
    "calendar_next_event": {
        "type": "object",
        "properties": {
            "calendar_entity_id": {"type": "string"},
            "window_hours": {"type": "number"},
        },
    },
    "todoist_add_task": {
        "type": "object",
        "properties": {
            "content": {"type": "string"},
            "description": {"type": "string"},
            "due_string": {"type": "string"},
            "priority": {"type": "integer"},
            "labels": {"type": "array", "items": {"type": "string"}},
            "requester_id": {"type": "string"},
            "request_context": {"type": "object"},
            "speaker_verified": {"type": "boolean"},
            "approved": {"type": "boolean"},
            "approval_code": {"type": "string"},
        },
        "required": ["content"],
    },
    "todoist_list_tasks": {
        "type": "object",
        "properties": {
            "limit": {"type": "integer"},
            "format": {"type": "string", "description": "short (default) or verbose"},
        },
    },
    "pushover_notify": {
        "type": "object",
        "properties": {
            "message": {"type": "string"},
            "title": {"type": "string"},
            "priority": {"type": "integer"},
        },
        "required": ["message"],
    },
    "get_time": {},
    "system_status": {},
    "system_status_contract": {},
    "jarvis_scorecard": {},
    "memory_add": {
        "type": "object",
        "properties": {
            "text": {"type": "string"},
            "kind": {"type": "string", "description": "note, profile, summary, task, etc."},
            "scope": {
                "type": "string",
                "description": "Memory scope: preferences, people, projects, or household_rules.",
            },
            "tags": {"type": "array", "items": {"type": "string"}},
            "importance": {"type": "number", "minimum": 0.0, "maximum": 1.0},
            "sensitivity": {"type": "number", "minimum": 0.0, "maximum": 1.0},
            "source": {"type": "string"},
            "allow_pii": {"type": "boolean"},
        },
        "required": ["text"],
    },
    "memory_update": {
        "type": "object",
        "properties": {
            "memory_id": {"type": "integer"},
            "text": {"type": "string"},
            "allow_pii": {"type": "boolean"},
        },
        "required": ["memory_id", "text"],
    },
    "memory_forget": {
        "type": "object",
        "properties": {
            "memory_id": {"type": "integer"},
        },
        "required": ["memory_id"],
    },
    "memory_search": {
        "type": "object",
        "properties": {
            "query": {"type": "string"},
            "limit": {"type": "integer"},
            "max_sensitivity": {"type": "number"},
            "include_sensitive": {"type": "boolean"},
            "hybrid_weight": {"type": "number"},
            "decay_enabled": {"type": "boolean"},
            "decay_half_life_days": {"type": "number"},
            "mmr_enabled": {"type": "boolean"},
            "mmr_lambda": {"type": "number"},
            "sources": {"type": "array", "items": {"type": "string"}},
            "scopes": {"type": "array", "items": {"type": "string"}},
        },
        "required": ["query"],
    },
    "memory_status": {
        "type": "object",
        "properties": {
            "warm": {"type": "boolean"},
            "sync": {"type": "boolean"},
            "optimize": {"type": "boolean"},
            "vacuum": {"type": "boolean"},
        },
    },
    "memory_recent": {
        "type": "object",
        "properties": {
            "limit": {"type": "integer"},
            "kind": {"type": "string"},
            "sources": {"type": "array", "items": {"type": "string"}},
            "scopes": {"type": "array", "items": {"type": "string"}},
        },
    },
    "memory_summary_add": {
        "type": "object",
        "properties": {
            "topic": {"type": "string"},
            "summary": {"type": "string"},
        },
        "required": ["topic", "summary"],
    },
    "memory_summary_list": {
        "type": "object",
        "properties": {
            "limit": {"type": "integer"},
        },
    },
    "task_plan_create": {
        "type": "object",
        "properties": {
            "title": {"type": "string"},
            "steps": {"type": "array", "items": {"type": "string"}},
        },
        "required": ["title", "steps"],
    },
    "task_plan_list": {
        "type": "object",
        "properties": {
            "open_only": {"type": "boolean"},
        },
    },
    "task_plan_update": {
        "type": "object",
        "properties": {
            "plan_id": {"type": "integer"},
            "step_index": {"type": "integer", "description": "0-based index"},
            "status": {"type": "string", "description": "pending, in_progress, blocked, done"},
        },
        "required": ["plan_id", "step_index", "status"],
    },
    "task_plan_summary": {
        "type": "object",
        "properties": {
            "plan_id": {"type": "integer"},
        },
        "required": ["plan_id"],
    },
    "task_plan_next": {
        "type": "object",
        "properties": {
            "plan_id": {"type": "integer"},
        },
    },
    "tool_summary": {
        "type": "object",
        "properties": {
            "limit": {"type": "integer"},
        },
    },
    "tool_summary_text": {
        "type": "object",
        "properties": {
            "limit": {"type": "integer"},
        },
    },
    "skills_list": {
        "type": "object",
        "properties": {},
    },
    "skills_enable": {
        "type": "object",
        "properties": {
            "name": {"type": "string"},
        },
        "required": ["name"],
    },
    "skills_disable": {
        "type": "object",
        "properties": {
            "name": {"type": "string"},
        },
        "required": ["name"],
    },
    "skills_version": {
        "type": "object",
        "properties": {
            "name": {"type": "string"},
        },
        "required": ["name"],
    },
    "proactive_assistant": {
        "type": "object",
        "properties": {
            "action": {
                "type": "string",
                "description": (
                    "briefing | anomaly_scan | routine_suggestions | "
                    "follow_through | event_digest | nudge_decision"
                ),
            },
            "mode": {"type": "string", "description": "morning or evening (for briefing)."},
            "calendar": {"type": "array", "items": {"type": "object"}},
            "reminders": {"type": "array", "items": {"type": "object"}},
            "weather": {"type": "object"},
            "home_state": {"type": "object"},
            "devices": {"type": "array", "items": {"type": "object"}},
            "history": {"type": "array", "items": {"type": "object"}},
            "opt_in": {"type": "boolean"},
            "pending_actions": {"type": "array", "items": {"type": "object"}},
            "confirm": {"type": "boolean"},
            "digest_items": {"type": "array", "items": {"type": "object"}},
            "snooze_minutes": {"type": "integer"},
            "policy": {"type": "string"},
            "quiet_window_active": {"type": "boolean"},
            "now": {"type": "number"},
            "max_dispatch": {"type": "integer"},
            "candidates": {"type": "array", "items": {"type": "object"}},
            "context": {"type": "object"},
        },
        "required": ["action"],
    },
    "memory_governance": {
        "type": "object",
        "properties": {
            "action": {"type": "string", "description": "partition | quality_audit | cleanup"},
            "user": {"type": "string"},
            "shared_scopes": {"type": "array", "items": {"type": "string"}},
            "private_scopes": {"type": "array", "items": {"type": "string"}},
            "stale_days": {"type": "number"},
            "apply": {"type": "boolean"},
            "limit": {"type": "integer"},
        },
        "required": ["action"],
    },
    "identity_trust": {
        "type": "object",
        "properties": {
            "action": {"type": "string", "description": "session_confidence | policy_set | policy_get | guest_start | guest_validate | guest_end | household_upsert | household_list | household_remove"},
            "voice_confidence": {"type": "number"},
            "operator_hint": {"type": "string"},
            "domain": {"type": "string"},
            "required_profile": {"type": "string"},
            "requires_step_up": {"type": "boolean"},
            "guest_id": {"type": "string"},
            "guest_session_token": {"type": "string"},
            "ttl_sec": {"type": "number"},
            "capabilities": {"type": "array", "items": {"type": "string"}},
            "user": {"type": "string"},
            "role": {"type": "string"},
            "trust_level": {"type": "string"},
            "exceptions": {"type": "array", "items": {"type": "string"}},
        },
        "required": ["action"],
    },
    "home_orchestrator": {
        "type": "object",
        "properties": {
            "action": {
                "type": "string",
                "description": (
                    "plan | execute | area_policy_set | area_policy_list | automation_suggest | "
                    "automation_create | automation_apply | automation_rollback | automation_status | "
                    "task_start | task_update | task_list"
                ),
            },
            "request_text": {"type": "string"},
            "plan": {"type": "object"},
            "actions": {"type": "array", "items": {"type": "object"}},
            "area": {"type": "string"},
            "policy": {"type": "object"},
            "history": {"type": "array", "items": {"type": "object"}},
            "task_id": {"type": "string"},
            "status": {"type": "string"},
            "progress": {"type": "number"},
            "notes": {"type": "string"},
            "alias": {"type": "string"},
            "automation_id": {"type": "string"},
            "draft_id": {"type": "string"},
            "trigger": {"type": "object"},
            "condition": {"type": "array", "items": {"type": "object"}},
            "dry_run": {"type": "boolean"},
            "confirm": {"type": "boolean"},
            "ha_apply": {"type": "boolean"},
        },
        "required": ["action"],
    },
    "skills_governance": {
        "type": "object",
        "properties": {
            "action": {"type": "string", "description": "negotiate | dependency_health | quota_set | quota_get | quota_check | harness_run | bundle_sign | sandbox_template"},
            "requested_capabilities": {"type": "array", "items": {"type": "string"}},
            "name": {"type": "string"},
            "rate_per_min": {"type": "integer"},
            "cpu_sec": {"type": "number"},
            "outbound_calls": {"type": "integer"},
            "usage": {"type": "object"},
            "fixtures": {"type": "array", "items": {"type": "object"}},
            "bundle": {"type": "object"},
            "template": {"type": "string"},
        },
        "required": ["action"],
    },
    "planner_engine": {
        "type": "object",
        "properties": {
            "action": {
                "type": "string",
                "description": (
                    "plan | task_graph_create | task_graph_update | task_graph_resume | deferred_schedule | "
                    "deferred_list | self_critique | autonomy_schedule | autonomy_checkpoint | "
                    "autonomy_cycle | autonomy_status"
                ),
            },
            "goal": {"type": "string"},
            "steps": {"type": "array", "items": {"type": "object"}},
            "graph_id": {"type": "string"},
            "node_id": {"type": "string"},
            "status": {"type": "string"},
            "title": {"type": "string"},
            "execute_at": {"type": "number"},
            "payload": {"type": "object"},
            "plan": {"type": "object"},
            "limit": {"type": "integer"},
            "risk": {"type": "string"},
            "requires_checkpoint": {"type": "boolean"},
            "checkpoint_id": {"type": "string"},
            "approved": {"type": "boolean"},
            "approved_checkpoints": {"type": "array", "items": {"type": "string"}},
            "recurrence_sec": {"type": "number"},
            "now": {"type": "number"},
        },
        "required": ["action"],
    },
    "quality_evaluator": {
        "type": "object",
        "properties": {
            "action": {"type": "string", "description": "weekly_report | dataset_run | reports_list"},
            "wins": {"type": "array", "items": {"type": "string"}},
            "regressions": {"type": "array", "items": {"type": "string"}},
            "report_path": {"type": "string"},
            "dataset": {"type": "array", "items": {"type": "object"}},
            "strict": {"type": "boolean"},
            "limit": {"type": "integer"},
        },
        "required": ["action"],
    },
    "embodiment_presence": {
        "type": "object",
        "properties": {
            "action": {"type": "string", "description": "expression_library | gaze_calibrate | gesture_profile | privacy_posture | safety_envelope | status"},
            "intent": {"type": "string"},
            "certainty_band": {"type": "string"},
            "micro_expression": {"type": "string"},
            "user": {"type": "string"},
            "distance_cm": {"type": "number"},
            "seat_offset_deg": {"type": "number"},
            "emotion": {"type": "string"},
            "importance": {"type": "string"},
            "amplitude": {"type": "number"},
            "state": {"type": "string"},
            "reason": {"type": "string"},
            "proximity_limit_cm": {"type": "number"},
            "hardware_state": {"type": "string"},
        },
        "required": ["action"],
    },
    "integration_hub": {
        "type": "object",
        "properties": {
            "action": {
                "type": "string",
                "description": (
                    "calendar_upsert | calendar_delete | notes_capture | messaging_flow | commute_brief | "
                    "shopping_orchestrate | research_workflow | release_channel_get | release_channel_set | "
                    "release_channel_check"
                ),
            },
            "confirm": {"type": "boolean"},
            "event_id": {"type": "string"},
            "event": {"type": "object"},
            "backend": {"type": "string"},
            "path": {"type": "string"},
            "title": {"type": "string"},
            "content": {"type": "string"},
            "calendar_entity_id": {"type": "string"},
            "start": {"type": "string"},
            "end": {"type": "string"},
            "summary": {"type": "string"},
            "description": {"type": "string"},
            "location": {"type": "string"},
            "event_payload": {"type": "object"},
            "channel": {"type": "string"},
            "phase": {"type": "string"},
            "message": {"type": "string"},
            "subject": {"type": "string"},
            "to": {"type": "string"},
            "traffic": {"type": "object"},
            "transit": {"type": "object"},
            "items": {"type": "array", "items": {"type": "string"}},
            "allow_web": {"type": "boolean"},
            "query": {"type": "string"},
            "citations": {"type": "array", "items": {"type": "string"}},
            "workspace": {"type": "string"},
        },
        "required": ["action"],
    },
}

SERVICE_RUNTIME_REQUIRED_FIELDS: dict[str, set[str]] = {
    "smart_home": {"domain", "action", "entity_id"},
    "smart_home_state": {"entity_id"},
    "home_assistant_capabilities": {"entity_id"},
    "home_assistant_conversation": {"text"},
    "home_assistant_todo": {"action", "entity_id"},
    "home_assistant_timer": {"action", "entity_id"},
    "home_assistant_area_entities": {"area"},
    "media_control": {"entity_id", "action"},
    "weather_lookup": {"location"},
    "webhook_trigger": {"url"},
    "webhook_inbound_list": set(),
    "webhook_inbound_clear": set(),
    "slack_notify": {"message"},
    "discord_notify": {"message"},
    "email_send": {"subject", "body"},
    "email_summary": set(),
    "dead_letter_list": set(),
    "dead_letter_replay": set(),
    "timer_create": {"duration"},
    "timer_list": set(),
    "timer_cancel": set(),
    "reminder_create": {"text", "due"},
    "reminder_list": set(),
    "reminder_complete": {"reminder_id"},
    "reminder_notify_due": set(),
    "calendar_events": set(),
    "calendar_next_event": set(),
    "todoist_add_task": {"content"},
    "todoist_list_tasks": set(),
    "pushover_notify": {"message"},
    "get_time": set(),
    "system_status": set(),
    "system_status_contract": set(),
    "jarvis_scorecard": set(),
    "memory_add": {"text"},
    "memory_update": {"memory_id", "text"},
    "memory_forget": {"memory_id"},
    "memory_search": {"query"},
    "memory_status": set(),
    "memory_recent": set(),
    "memory_summary_add": {"topic", "summary"},
    "memory_summary_list": set(),
    "task_plan_create": {"title", "steps"},
    "task_plan_list": set(),
    "task_plan_update": {"plan_id", "step_index", "status"},
    "task_plan_summary": {"plan_id"},
    "task_plan_next": set(),
    "tool_summary": set(),
    "tool_summary_text": set(),
    "skills_list": set(),
    "skills_enable": {"name"},
    "skills_disable": {"name"},
    "skills_version": {"name"},
    "proactive_assistant": {"action"},
    "memory_governance": {"action"},
    "identity_trust": {"action"},
    "home_orchestrator": {"action"},
    "skills_governance": {"action"},
    "planner_engine": {"action"},
    "quality_evaluator": {"action"},
    "embodiment_presence": {"action"},
    "integration_hub": {"action"},
}
